- package.json
> 🐞 Restore the sass-package

- .husky/pre-commit
- package.json
- src/entities/master-password/test/create-master-tool.spec.ts
Для Master tool теперь есть тест. Запуск тестов теперь включен в pre-commit hook.
> :white_check_mark: Try Vitest

- src/entities/services-config/types.ts
В рамках данной задачи будет сделано:
- Разработан тип для представления конфига сервисов приложением;
- Разработан тип для сохранения конфига сервисов в JSON;
- ~~Разработаны функции-переводчики каждого типа в другой.~~
> 🏷️ Develop a configuration interface

- src/entities/master-password/test/create-master-tool.spec.ts
> 🐛 Typo in entities/master-password/test/create-master-tool.spec.ts

- src/entities/services-config/lib/compress-config.ts
- src/entities/services-config/lib/decompress-config.ts
- src/entities/services-config/test/compress-config.spec.ts
- src/entities/services-config/test/decompress-config.spec.ts
- src/entities/services-config/test/examples.ts
- src/entities/services-config/types.ts
В рамках выполнения задачи будут реализованы функции `compressConfig` и `decompressConfig`, а также тесты к ним.
> ✨ Config compression/decompression utils

- src/shared/lib/generate-password.ts
- src/shared/test/generate-password.spec.ts
В рамках выполнения данной задачи будет разработана функция `generatePassword` и тесты к ней.
> ✨ Create a password generation function

- src/entities/master-tool/lib/create-master-tool.ts
- src/shared/index.ts
- src/shared/lib/aes.ts
- src/shared/lib/text-tools.ts
- src/shared/test/aes.spec.ts
В рамках этой задачи реализованы функции симметричного зашифровывания и расшифровывания данных. Кроме того, были созданы вспомогательные функции: чтение буфера из hex-строки и создание строки из буфера, содержащего её данные. Создание ключа симметричного шифрования было вынесено в слой `shared` из вспомогательных функций сущности MasterTool для повторного использования. Написаны тесты новой функциональности.
> ✨ Symmetric encryption/decryption

- src/entities/master-tool/index.ts
- src/entities/master-tool/lib/decrypt-hex.ts
- src/entities/master-tool/model/master-tool.ts
- src/entities/services-config/index.ts
- src/entities/services-config/model/service-config.ts
- src/features/configuration-export/components/ConfigEncryptedCopy.vue
- src/features/configuration-export/components/ConfigFileExport.vue
- src/features/configuration-export/components/ConfigRawJsonCopy.vue
- src/features/configuration-export/hooks/clipboard-copy.ts
- src/features/configuration-export/hooks/file-export.ts
- src/features/configuration-export/index.ts
- src/features/configuration-export/lib/get-encrypted-config.ts
- src/features/configuration-import/components/ConfigFileImport.vue
- src/features/configuration-import/components/ConfigTextImport.vue
- src/features/configuration-import/components/DeleteConfig.vue
- src/features/configuration-import/hooks/delete-config.ts
- src/features/configuration-import/hooks/file-import.ts
- src/features/configuration-import/hooks/text-import.ts
- src/features/configuration-import/index.ts
- src/features/configuration-import/lib/import-text.ts
- src/features/configuration-import/lib/parse-config.ts
- src/features/configuration-import/lib/set-configuration.ts
- src/features/entry/actions/enter.ts
- src/pages/work-screen/components/WorkScreen.vue
- src/widgets/configuration-panel/components/ConfigurationPanel.vue
- src/widgets/configuration-panel/index.scss
- src/widgets/configuration-panel/index.ts
В этой задаче будет создана панель конфигурации сервисов.
> ✨ Configuration widget

- src/pages/work-screen/components/WorkScreen.vue
- src/widgets/short-hash/components/ShortHash.vue
- src/widgets/short-hash/index.ts
Короткий хэш обрезается до 6 символов и выводится на рабочий экран в нереактивном виде.
> ✨ Display a short hash on the working screen

- src/entities/services-config/lib/compress-config.ts
- src/entities/services-config/lib/creation-tools.ts
- src/entities/services-config/lib/custom-services.ts
- src/entities/services-config/lib/decompress-config.ts
- src/entities/services-config/types.ts
- src/features/service-management/components/AddLoginToCustomService.vue
- src/features/service-management/components/CustomService.vue
- src/features/service-management/components/LoginItem.vue
- src/features/service-management/components/LoginsList.vue
- src/features/service-management/components/ServicePreferences.vue
- src/features/service-management/hooks/add-login-to-custom-service.ts
- src/features/service-management/hooks/login-item.ts
- src/features/service-management/index.scss
- src/features/service-management/lib/get-password-of-login.ts
- src/shared/index.ts
- src/shared/lib/charset.ts
- src/shared/lib/password-length.ts
- src/shared/test/generate-password.spec.ts
- src/shared/ui/copy-button/CopyButton.vue
- src/shared/ui/password-length-group/PasswordLengthGroup.vue
Эта задача завершает собой базовую функциональность приложения. В сервисах перечисляются логины, их можно добавлять и удалять, менять версию пароля, а также копировать логин и пароль в буфер обмена.
> ✨ List of logins

- .github/workflows/ci.yaml
- package.json
Runner will run on PR and Push to dev|main branch.
**CI is divided into several stages:**
- Linting
- Type Check
- Tests
> Github workflow added

- .husky/pre-commit
- package.json
Husky hasn't penetrated our repository that deep. It wasn't hard to cut it out.
> 🔧 Get rid of husky

- src/entities/services-config/model/service-config.ts
- src/features/service-management/components/LoginItem.vue
- src/features/service-management/hooks/login-item.ts
This will create a button and a function to remove an existing login from the service.
> ✨ Add option to delete login

- .stylelintrc
- src/app/style/normalize.scss
- src/features/service-management/components/LoginItem.vue
- src/features/service-management/components/ServiceItem.vue
- src/features/service-management/index.scss
- src/features/service-management/style/login.scss
- src/features/service-management/style/service.scss
In the beginning, the main thing is to ensure accessibility. The beauty of the interface is not important yet.
> 💄 Adapt layout to small screens

- src/features/configuration-import/hooks/delete-config.ts
- src/features/entry/actions/exit.ts
- src/features/service-management/hooks/service-deleting.ts
In this task, user confirmation prompts will be added for all deletions or other sensitive operations.
> ♻️ Replace some alerts with confirms

- src/features/service-management/components/ServiceAdder.vue
- src/features/services-filter/components/ServicesFilter.vue
- src/features/services-filter/hooks/hotkey-focus.ts
- src/features/services-filter/index.ts
- src/features/services-filter/model/services-filter.ts
- src/shared/index.ts
- src/shared/lib/element-ref.ts
- src/widgets/services-list/components/ServicesList.vue
- src/widgets/services-list/index.scss
In this task, I have added a text input into which you can enter part of the service name. The list of services will only show services that contain this part in their name.
> ✨ Filter-search for services by name

- src/features/entry/components/MasterForm.vue
- src/features/entry/hooks/master-form.ts
At first I just wanted to add the autofocus attribute. It didn't work, the focus is set only when entering the application, but not when exiting the work screen. So I did it in a hook.
> ✨ Focus master-password input

- LICENSE
- README.md
In this task, a description of the repository is added as well as a license.
> 📝 README.md

- README.md
Change dev to main in one place.
> Pre-release fix

- README.md
- package.json
- vite.config.ts
Fixed bug and repository description.
> 🐞 Build for standalone

- src/app/style/index.scss
- src/app/style/typography.scss
I decided not to connect an external font, but to use a common system one. This is due to the fact that it is not clear how to build an external font in standalone mode.
> 💄 Connect font

- src/entities/aside-window/index.scss
- src/pages/work-screen/components/WorkScreen.vue
- src/pages/work-screen/index.scss
- src/pages/work-screen/index.ts
- src/pages/work-screen/style/work-screen.scss
- src/pages/work-screen/style/work-wrapper.scss
In this task, the main work screen layout styles will be redesigned.
> 💄 Work screen wrapper

- src/features/services-filter/components/ServicesFilter.vue
- src/features/services-filter/index.scss
- src/features/services-filter/index.ts
- src/widgets/services-header/components/ServicesHeader.vue
- src/widgets/services-header/index.scss
- src/widgets/services-header/index.ts
In this task, the service header will be decorated. Closes #96.
> 💄 Services header

- src/entities/aside-window/components/AppAside.vue
- src/entities/aside-window/index.scss
- src/features/save-configuration/components/SaveCancelConfig.vue
- src/shared/icons/IconCross.vue
- src/shared/icons/index.ts
- src/widgets/work-header/components/ConfigurationAside.vue
In this task, the Aside window will have a beautiful header.
> 💄 Aside header

- src/features/entry/components/MasterForm.vue
- src/features/entry/index.scss
- src/features/entry/index.ts
- src/pages/password-entry/components/PasswordEntry.vue
- src/pages/password-entry/index.scss
- src/pages/password-entry/index.ts
- src/widgets/app-info/components/AppInfo.vue
- src/widgets/app-info/components/AppInfoLink.vue
- src/widgets/app-info/index.scss
- src/widgets/app-info/index.ts
In this task, the master password entry page will be redesigned.
> ♻️ Remake the password entry

- src/features/service-management/hooks/service-details.ts
- src/widgets/services-header/hooks/service-header.ts
After this task, when entering the service name and login, the program will trim the spaces.
> ✨ Trim names

- src/entities/aside-window/components/AppAside.vue
- src/features/service-management/components/LoginItem.vue
- src/features/service-management/components/ServiceItem.vue
This task adds titles to all missing buttons.
> ✨ All IconButtons must have a title

- package.json
- tsconfig.app.json
- tsconfig.config.json
> 📦 Update package versions

- src/app/style/normalize.scss
After this task inputs on iPhones will be without border-radius.
> 🐞 Normalize input border-radius

- src/app/style/helpers.scss
- src/app/style/normalize.scss
- src/entities/aside-window/index.scss
We fix two bugs:
- Too long service name broke layout;
- On iPhones, the edges of the text fields were rounded off.
> :bookmark: Release 1.1.1

- package.json
- src/features/service-management/components/ServiceDetails.vue
- tsconfig.app.json
- tsconfig.config.json
Dependency versions are now what they were before the last change.
> ⏪ Rollback dependency versions

- src/main.ts
- src/widgets/app-info/components/AppInfo.vue
- src/widgets/app-info/components/AppInfoLink.vue
- src/widgets/app-info/components/GitHubLink.vue
Now on the main page there is a link to the Telegram channel.
> ✨ Add a link to the Telegram channel to the main page

- public/sw.js
The current version of Passcryptum has been added to sw.js.
> :bookmark: Set version

- src/entities/aside-window/index.scss
Now aside works fine on small screens.
> :ambulance: Fix aside on small screens

- public/sw.js
Updated version in sw.js to 1.2.1.
> 🔖 Release 1.2.1

- .stylelintrc
- public/sw.js
- src/entities/aside-window/index.scss
- src/pages/password-entry/index.scss
- src/pages/work-screen/style/work-screen.scss
- src/pages/work-screen/style/work-wrapper.scss
- src/widgets/services-header/index.scss
Changed `media-feature-range-notation` rule for Stylelint to "prefix". This should fix the layout issue on the iPhone.
> 🔖 Hotfix v1.2.2: media notation

- public/sw.js
- src/shared/ui/copy-button/CopyButton.vue
Added a polyfill to copy strings to the clipboard in Firefox.
> 🐛 Fix copying ability in Firefox

- src/app/index.ts
- src/app/lib/register-sw.ts
- src/main.ts
Now the ServiceWorker will connect using the function from the app layer.
> ⏪ Return ServiceWorker

- src/features/service-details/components/ServicePreferences.vue
- src/features/service-details/index.scss
I replaced Slider with RadioGroup and now everything works great.
> 🐛 Turn password length selector into a radio group

- src/widgets/services-list/components/ServiceItem.vue
- src/widgets/services-list/components/ServicesList.vue
It seems that we managed to solve this problem using the "expanded-names" property.
> ✨ Expand the only service in the list

- src/entities/session/model/public.ts
- src/features/storage/components/ImportFromText.vue
The importServices function now saves data after a merge. The ImportFromText component logic has been updated to work with the new behavior of the importServices function.
> 🐛 Fix services import
